version: "3"
services:
  redis:
    image: "redis:4"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    restart: on-failure
    volumes:
      - ~/bridge_data/redis:/data
  rabbit:
    image: "rabbitmq:3-management"
    hostname: rabbit
    environment:
      - RABBITMQ_NODENAME=node@rabbit
    volumes:
      - ~/bridge_data/rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
    restart: on-failure
  bridge:
    build: .
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - QUEUE_URL=amqp://rabbit
      - REDIS_URL=redis://redis
    command: "true"
    restart: on-failure